services:

  rosbot-xl:
    image: husarion/rosbot-xl:humble-0.3.0-20230204
    network_mode: host
    ipc: host
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: ros2 launch rosbot_xl_bringup bringup.launch.py mecanum:=${MECANUM:-True}

  microros:
    image: husarion/micro-ros-agent:humble-3.1.2-20230204-stable
    network_mode: host
    ipc: host
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
    command: ros2 run micro_ros_agent micro_ros_agent udp4 --port 8888

  rplidar:
    image: husarion/rplidar:humble-1.0.1-20230206-stable
    network_mode: host
    ipc: host
    devices:
      - ${LIDAR_SERIAL:?err}:/dev/ttyUSB0
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: ros2 launch sllidar_ros2 sllidar_launch.py serial_baudrate:=${LIDAR_BAUDRATE:-115200}

  navigation:
    image: husarion/navigation2:humble-1.1.5-20230206-stable
    network_mode: host
    ipc: host
    volumes:
      - ./config/${NAV2_PARAMS:-nav2_params.yaml}:/nav2_params.yaml
      # modified behaviour tree that doesn't replan global path
      # (it is used only when specified by default_nav_to_pose_bt_xml parameter)
      - ./config/navigate_w_recovery.xml:/navigate_w_recovery.xml
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: >
      ros2 launch nav2_bringup navigation_launch.py
        params_file:=/nav2_params.yaml
        use_sim_time:=${USE_SIM_TIME:-False}

  localization:
    image: husarion/navigation2:humble-1.1.5-20230206-stable
    network_mode: host
    ipc: host
    volumes:
      - ./config/${AMCL_PARAMS:-amcl_params.yaml}:/amcl_params.yaml
      - ./maps:/maps
    environment:
      - DDS_CONFIG
      - RMW_IMPLEMENTATION
    command: >
      ros2 launch nav2_bringup localization_launch.py
        params_file:=/amcl_params.yaml
        map:=/maps/map.yaml
        use_sim_time:=${USE_SIM_TIME:-False}